Lite local
Ostorlab/ostorlab pull request #178
Opened 2022-03-01 13:01 UTC by RabsonJ

2022-03-01 13:07 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +class LocalRuntime(runtime.Runtime):
```suggestion
class LiteLocalRuntime(runtime.Runtime):
```

2022-03-01 13:11 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/__init__.py
> +from .runtime import LocalRuntime
```suggestion
from .runtime import LiteLocalRuntime
```

2022-03-01 13:12 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/__init__.py
> +"""Ostorlab local runtime modules. this module takes care of launching a scan in the local machine."""
```suggestion
"""Ostorlab lite local runtime modules. this module takes care of launching a scan in the local machine but with little setup, like no MQ service, no scan persistence and no defaults agents are started."""
```

2022-03-01 13:12 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/agent_runtime.py
> +"""Runtime agent module gives access to methods to create the specific agent configurations & run the agent.
I think you can delete this one and simply use the one from localruntime for the moment.

2022-03-01 13:13 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +"""Local runtime runs agents locally.
```suggestion
"""Lite local runtime runs agents locally with limited setup, like no MQ service and no defaults agents.
```

2022-03-01 13:14 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +The local runtime requires Docker Swarm to run robust long-running services with a set of configured services, like
The example is not correct, because it doesn't start rabbitmq.

2022-03-01 13:14 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +NETWORK_PREFIX = 'ostorlab_local_network'
```suggestion
NETWORK_PREFIX = 'ostorlab_lite_local_network'
```

2022-03-01 13:14 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +TRACKER_AGENT_DEFAULT = 'agent/ostorlab/tracker'
This should be removed.

2022-03-01 13:15 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +LOCAL_PERSIST_VULNZ_AGENT_DEFAULT = 'agent/ostorlab/local_persist_vulnz'
This one as well.

2022-03-01 13:15 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +DEFAULT_AGENTS = [
This is also not needed.

2022-03-01 13:15 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +def _get_task_ips(service: docker_models_services.Service) -> List[str]:
This method is not used. It can be deleted in the existing runtime as well.

2022-03-01 13:16 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +def _is_agent_status_ok(ip: str) -> bool:
This method is also not used and should be deleted from the other runtime as well.

2022-03-01 13:16 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +    """Local runtime runes agents locally using Docker Swarm.
```suggestion
    """Lite local runtime runes agents locally using Docker Swarm.
```

2022-03-01 13:16 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +    Local runtime starts a Vanilla RabbitMQ service, starts all the agents listed in the `AgentRunDefinition`, checks
This comment is not correct.

2022-03-01 13:17 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +        self.follow = []
Follow is not needed. Should, be removed.

2022-03-01 13:18 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +        return f'{NETWORK_PREFIX}_{self.name}'
Missing docstring, should be added to the existing runtime as well.

2022-03-01 13:18 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +            self._start_pre_agents()
There are no pre_agents. Should be removed.

2022-03-01 13:18 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +            console.info('Starting post-agents')
There are no post_agents should be removed.

2022-03-01 13:21 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +    def _update_scan_progress(self, progress: str):
This should be removed.

2022-03-01 13:21 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +    def _start_pre_agents(self):
This should be removed.

2022-03-01 13:21 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +    def _start_post_agents(self):
This should be removed.

2022-03-01 13:21 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +    def _start_tracker_agent(self):
This should be removed.

2022-03-01 13:22 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +    def _start_persist_vulnz_agent(self):
This should be removed.

2022-03-01 13:23 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +        if page is not None:
This is method is not supported in the lite local runtime. It should throw a NotImplementedError exception.

2022-03-01 14:58 UTC, 3asm requested changes
Some minor comments, otherwise looks good.

2022-03-01 14:58 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +        self._scan_db: Optional[models.Scan] = None
Needs to be deleted.

2022-03-01 14:58 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +        if self._scan_db is not None:
Actually, this code is not correct. Need to be fixed. Actually the scan id should be passed from the constructor.

2022-03-01 14:58 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +
Remove empty line.

2022-03-01 14:58 UTC, 3asm commented on src/ostorlab/runtimes/lite_local/runtime.py
> +
Remove empty line.

2022-03-01 15:53 UTC, RabsonJ commented on src/ostorlab/runtimes/lite_local/agent_runtime.py
> +        # self.agent.bus_url = self.bus_host
Not sure what should be here

2022-03-01 15:53 UTC, RabsonJ commented on src/ostorlab/runtimes/lite_local/agent_runtime.py
> +        # self.agent.bus_management_url = self.mq_service.management_url
Not sure what should be here

2022-03-02 15:02 UTC, RabsonJ commented on src/ostorlab/cli/scan/scan.py
> +@click.option('--bus-url', help='Bus URL, this flag is restricted to the local runtime.', required=False)
Yes! thanks for spotting that

2022-03-02 15:09 UTC, merged