Add ci run
Ostorlab/ostorlab pull request #179
Opened 2022-03-01 16:22 UTC by amine3

2022-03-02 14:51 UTC, RabsonJ commented on tests/cli/ci_scan/run/run_test.py
> +    assert isinstance(result.exception, BaseException)
Missing a newline at the end of the file.

2022-03-02 16:44 UTC, 3asm requested changes

2022-03-02 16:44 UTC, 3asm commented on src/ostorlab/apis/runners/authenticated_runner.py
>          """Constructs all the necessary attributes for the object.
Would be good to have a docstring, this is getting complicated.

2022-03-02 16:44 UTC, 3asm commented on src/ostorlab/apis/runners/authenticated_runner.py
>          """Constructs all the necessary attributes for the object.
I meant explain the args.

2022-03-02 16:44 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/assets/android.py
> +"""Asset of type .APK package file.
I would recommend keeping the same assets we have on scan run. Meaning android_apk, android_aab, etc.

2022-03-02 16:44 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/assets/android.py
> +"""Asset of type .APK package file.
This also means adding an asset package_name and bundle_id

2022-03-02 16:44 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/run.py
> +        check_scan_process = multiprocessing.Process(
Why does this need to run on a separate process?

2022-03-02 16:44 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/run.py
> +def check_scan_periodically(runner, scan_id):
Private method, start with _

2022-03-02 16:44 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/run.py
> +def check_scan_periodically(runner, scan_id):
Type hint please.

2022-03-02 16:44 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/run.py
> +def check_scan_risk_rating(scan_risk_rating, break_on_risk_rating, ci_logger):
Same here, type hint and private method.

2022-03-03 08:40 UTC, 3asm requested changes

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/apis/runners/authenticated_runner.py
>          """Constructs all the necessary attributes for the object.
Why is the docstring added this way, just use the standard google docstring way.

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/ci_logger/github_logger.py
> +class Logger(abc.ABC):
This class should inherit from the abstract logger. This code is incorrect.

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/ci_logger/console_logger.py
> +class Logger(abc.ABC):
Same here, this code should inherit from the abstract logger.

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/run.py
> +    'potentially': 3
What happens to the others we have? I also think this is already defined somewhere in the code, we should not duplicate it.

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/run.py
> +    'console': console_logger.Logger(),
I would prefer only having a reference to the class and not creating a full instance that will not be used.

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/apis/runners/authenticated_runner.py
> +        if api_key:
this can be simplified to:
self._api_key = api_key or self._configuration_manager.get_api_key()

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/apis/scan_create.py
> +class RiskRating(enum.Enum):
This class should have a method to help with sorting and priorization of risks.

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/apis/scan_create.py
> +class RiskRating(enum.Enum):
Should also be put in a common somewhere.

2022-03-03 08:40 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/assets/android_aab.py
> +    ci_logger = ctx.obj['ci_logger']
This has a lot of duplicate code between all the assets. I would suggest putting it in a method and use across the assets.

2022-03-03 11:33 UTC, 3asm approved these changes

2022-03-03 12:41 UTC, merged