Cloud runtime vuln describe
Ostorlab/ostorlab pull request #206
Opened 2022-03-10 13:28 UTC by mohsinenar

2022-03-10 13:29 UTC, mohsinenar commented on src/ostorlab/apis/scan_vulnz.py
> +"""Lists the remote vulnz."""
```suggestion
"""List remote scan vulnz."""
```

2022-03-10 13:29 UTC, mohsinenar commented on src/ostorlab/apis/vulnz_describe.py
> +"""Lists the remote vulnz."""
```suggestion
"""Fetch a single vuln."""
```

2022-03-10 13:30 UTC, mohsinenar commented on src/ostorlab/apis/vulnz_describe.py
> +    """Lists the remote vulnz of a scan."""
```suggestion
    """Fetch a single vuln ."""
```

2022-03-10 13:31 UTC, mohsinenar commented on src/ostorlab/apis/vulnz_describe.py
> +        """Defines the query to list the vulnz.
```suggestion
        """Defines the query to fetch a vuln.
```

2022-03-11 09:11 UTC, 3asm requested changes

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/cli/vulnz/describe/describe.py
> +        raise click.BadParameter('You should provide --scan-id. when using cloud runtime')
```suggestion
        raise click.BadParameter('Please provide --scan-id / -s when using the cloud runtime')
```

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/cli/vulnz/describe/describe.py
> +        raise click.BadParameter('You should provide --scan-id. or --vuln-id when using local runtime')
```suggestion
        raise click.BadParameter('Please provide --scan-id / -s or --vuln-id / -v when using local runtime')
```

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/cloud/runtime.py
> +                    'riskRating': styles.style_risk(vulnerability['detail']['riskRating'].upper()),
why is this camel case and the the other are not?

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/cloud/runtime.py
> +                'Risk Rating': 'riskRating',
same here.

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/cloud/runtime.py
> +                console.info('Show the next page?')
```suggestion
                console.info('Fetch next page?')
```

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/cloud/runtime.py
> +            'Risk rating': 'risk_rating',
```suggestion
            'Risk Rating': 'risk_rating',
```

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/cloud/runtime.py
> +            'Risk rating': 'risk_rating',
Be consist with the casing.

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/cloud/runtime.py
> +            'CVSS V3 Vector': 'cvss_v3_vector',
```suggestion
            'CVSSv3 Vector': 'cvss_v3_vector',
```

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/cloud/runtime.py
> +                    console.info('Show the next page?')
```suggestion
                    console.info('Fetch next page?')
```

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/cloud/runtime.py
> +            console.error(f'Scan with ID {scan_id} not found')
```suggestion
            console.error(f'Scan {scan_id} not found')
```

2022-03-11 09:11 UTC, 3asm commented on src/ostorlab/runtimes/local/runtime.py
> +            'Risk rating': 'risk_rating',
Please change the casing and CVSSv3 per previous comment.

2022-03-11 09:17 UTC, mohsinenar commented on setup.cfg
> +    markdownify
Noted. I'll create a ticket.

2022-03-11 10:58 UTC, 3asm approved these changes

2022-03-11 10:59 UTC, merged