Implement arch check
Ostorlab/ostorlab pull request #314
Opened 2022-07-27 16:35 UTC by jamu85

Raises an error if the runtime or agents installs are started on unsupported machine architecture.
As the issue is related to the docker requirements, I implemented the check in docker_requirements_checker.py
New supported architectures need to be added to the list of supported architectures.

The architecture is checked with a return value that's based on the kernel implementation of the uname(2)
 system call. So it might be necesarry to handle the same arch with various strings e.g. linux returns x86_64
 or AMD64 on windows.

On mac os, uname returns x86 even on arm64 if the process calling it is running via rosetta. Better parse for ARM
in platform.version() to determine the arch on mac os

2022-07-28 08:41 UTC, 3asm requested changes

2022-07-28 08:41 UTC, 3asm commented on src/ostorlab/cli/agent/install/install.py
> +    elif not docker_requirements_checker.is_sys_arch_supported():
Nice job figuring out where to add the checks.

2022-07-28 08:41 UTC, 3asm commented on src/ostorlab/cli/docker_requirements_checker.py
> +        """On mac os, uname returns x86 even on arm64 if the process calling it is running via rosetta. We parse for ARM
This should be a comment style, I think the linter will not pass this. As FYI, we apply Google style guide in the code base for consistency : https://google.github.io/styleguide/pyguide.html

2022-07-28 08:41 UTC, 3asm commented on src/ostorlab/cli/docker_requirements_checker.py
> +    supported_arch_types = ["x86_64", "AMD64"]
This is better put as a const at the top of the file for readability's sake.

2022-07-28 08:41 UTC, 3asm commented on src/ostorlab/cli/docker_requirements_checker.py
> +    if sys.platform == 'darwin' and 'ARM' in platform.version():
Great catch!

2022-07-28 11:30 UTC, jamu85 reviewed
Should be according to your request now

2022-07-28 13:11 UTC, 3asm approved these changes

2022-07-28 13:52 UTC, jamu85 commented
I could fix the linter issues, however, I have no idea how to solve the ssh key task for testing. Can this pr be closed?

2022-07-29 16:09 UTC, 3asm commented
I don't understand either why the SSH is failing. I am suspecting some permission bit. I believe we no longer need the SSH in the flow, but I need to double-check.

2022-07-29 16:09 UTC, merged