Add GCP exporter
Ostorlab/ostorlab pull request #344
Opened 2022-08-30 11:34 UTC by amine3

Add GCP exporter to OpenTelemetry Mixin using opentelemetry-exporter-gcp-trace

2022-08-30 13:31 UTC, mohsinenar commented on src/ostorlab/agent/mixins/agent_open_telemetry_mixin.py
> +from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter
don't import classes directly. 
```suggestion
from opentelemetry.exporter import cloud_trace
```

2022-08-30 13:31 UTC, mohsinenar commented on src/ostorlab/agent/mixins/agent_open_telemetry_mixin.py
> +        return CloudTraceSpanExporter(project_id=project_id)
```suggestion
        return cloud_trace.CloudTraceSpanExporter(project_id=project_id)
```

2022-08-30 14:30 UTC, 3asm requested changes

2022-08-30 14:30 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_open_telemetry_mixin.py
> +import os
Where is the unit test?

2022-08-30 14:30 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_open_telemetry_mixin.py
> +    def _get_gcp_exporter(self, parsed_url):
This requires some documentation one what is expected here, what is the format of the URL, etc.

2022-08-30 14:30 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_open_telemetry_mixin.py
> +        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = service_account_key
This warrant a comment on why.

2022-08-30 20:43 UTC, 3asm requested changes

2022-08-30 20:43 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_open_telemetry_mixin.py
> +            eg: gcp:project_1:/tmp/key.json
we should have the json content in the URL, we should not rely on external paths for passing credentials.

2022-08-30 20:54 UTC, 3asm requested changes

2022-08-31 07:47 UTC, 3asm approved these changes

2022-08-31 07:47 UTC, merged