Add asset location to protobuf and agent_report_vulnerability_mixin.
Ostorlab/ostorlab pull request #373
Opened 2022-10-14 16:12 UTC by mohsinenar

2022-10-18 11:19 UTC, deadly-panda commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +            MAP_ASSETS_NAMES[self.asset.__class__.__name__]: self.asset.__dict__,
I would've put the classes as keys of MAP_ASSETS_NAMES, & use type(self.asset) here.

2022-10-18 11:20 UTC, deadly-panda commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +            MAP_ASSETS_NAMES[self.asset.__class__.__name__]: self.asset.__dict__,
Also I would've used: `dataclasses.asdict(self.asset)` and avoid any magic functions.

2022-10-18 11:20 UTC, deadly-panda commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +                             asset_location: AssetLocation = None) -> None:
The name `asset_location` is confusing.

2022-10-18 11:21 UTC, deadly-panda commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +            'asset_location': asset_location.to_dict() if asset_location is not None else None
If it is None, do not emit it.

2022-10-18 11:25 UTC, deadly-panda commented on src/ostorlab/assets/ios_store.py
> +        return f'IOS store bundle_id ({self.path})'
```suggestion
        return f'IOS store bundle_id ({self.bundle_id})'
```

2022-10-18 11:28 UTC, deadly-panda commented on tests/agent/mixins/agent_report_vulnerability_mixin_test.py
> +    request.getfixturevalue(asset_location_fixture)
is this needed here ?

2022-10-18 11:34 UTC, deadly-panda commented on tests/conftest.py
> +        asset=ipv6_asset.IPv6(host='8.8.8.8'))
```suggestion
        asset=ipv6_asset.IPv6(host='2001:4860:4860::8888'))
```

2022-10-18 13:39 UTC, deadly-panda requested changes

2022-10-18 13:39 UTC, deadly-panda commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +                             vulnerability_location: VulnerabilityLocation = None) -> None:
```suggestion
                             vulnerability_location: Optional[VulnerabilityLocation] = None) -> None:
```

2022-10-18 13:39 UTC, deadly-panda commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +            'vulnerability_location': vulnerability_location.to_dict() if vulnerability_location is not None else None
don't put it in the dict if it's None.

2022-10-18 21:50 UTC, 3asm requested changes

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/agent/message/proto/v3/report/vulnerability/vulnerability.proto
> +    ostorlab.agent.message.proto.v3.asset.file.Message  file = 7;
```suggestion
    ostorlab.agent.message.proto.v3.asset.file.Message file = 7;
```

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/agent/message/proto/v3/report/vulnerability/vulnerability.proto
> +    ostorlab.agent.message.proto.v3.asset.file.android.apk.Message  android_apk = 9;
```suggestion
    ostorlab.agent.message.proto.v3.asset.file.android.aab.Message android_aab = 8;
    ostorlab.agent.message.proto.v3.asset.file.android.apk.Message android_apk = 9;
```

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +    """Asset Location MetaData Type"""
```suggestion
    """Asset location metadata type."""
```

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +    ipv4_asset.IPv4: 'ipv4',
The string thingy should an attribute of each asset. Centralizing it here is change error prone.

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +    type: MetaDataType
Metadata not MetaData. Please change everywhere.

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +    def to_dict(self) -> dict:
dict of what? Please ensure typing is correct and also run mypy on it this part.

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
> +            vulnerability_location:  asset location where the vulnerability was detected.
Please respect the order of the arguments.

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/assets/android_store.py
> +        return f'Android Store: {self.package_name}'
Please aligh the string to have the same format. Android Soter ({self.package_name}) is coherent with the rest.

2022-10-18 21:50 UTC, 3asm commented on src/ostorlab/assets/ios_store.py
> +        return f'IOS store bundle_id ({self.bundle_id})'
```suggestion
        return f'iOS Store ({self.bundle_id})'
```

Coherence, coherence, coherence!

2022-10-18 21:50 UTC, 3asm commented on tests/agent/mixins/agent_report_vulnerability_mixin_test.py
> +def testSendVulnerabilityMessageWithAssetLocation_whenKbEntryIsValid_emitVulnerabilityMessage(
```suggestion
def testSendVulnerabilityMessage_withVulnerabilityLocation_emitVulnerabilityMessageWithProperData(
```

2022-10-18 21:50 UTC, 3asm commented on tests/assets/asset_test.py
> +        def __init__(self, content):
It is a dataclass, why do you need to change the init method?

2022-10-19 12:04 UTC, 3asm approved these changes

2022-10-19 12:05 UTC, merged