update kb
Ostorlab/ostorlab pull request #427
Opened 2023-05-12 16:42 UTC by mohsinenar

- Update kb.
- Update kb.

2023-05-12 16:43 UTC, BlueSquare1 approved these changes

2023-05-15 16:48 UTC, BlueSquare1 submitted a review, later dismissed

2023-05-15 16:52 UTC, amine3 approved these changes

2023-05-15 16:52 UTC, deadly-panda requested changes

2023-05-15 16:52 UTC, deadly-panda commented on .github/workflows/pytest-linux.yml
>          python -m pip install -e .
Put the pytest workflow back please.

2023-05-15 16:54 UTC, rabsondev submitted a review, later dismissed

2023-05-15 16:55 UTC, amine3 submitted a review, later dismissed

2023-05-15 17:44 UTC, deadly-panda approved these changes

2023-05-15 17:45 UTC, merged