fix semver to 3.0.0
Ostorlab/ostorlab pull request #428
Opened 2023-05-15 18:48 UTC by mohsinenar

- Update kb.
- Update kb.
- Fix mypy error.
- Remove the use pytest-coverage-commentator action.
- Remove the use pytest-coverage-commentator action.
- Remove the use pytest-coverage-commentator action.
- Remove the use pytest-coverage-commentator action.
- Fix semver version to 3.0.0

2023-05-15 18:49 UTC, deadly-panda approved these changes

2023-05-15 18:51 UTC, amine3 approved these changes

2023-05-16 03:08 UTC, 3asm requested changes

2023-05-16 03:08 UTC, 3asm commented on setup.cfg
> +    semver==3.0.0
Bigger than 3. No need to be specific.

2023-05-16 09:41 UTC, mohsinenar commented on setup.cfg
> +version = 0.14.2
```suggestion
version=0.14.2
```

2023-05-16 10:13 UTC, 3asm approved these changes

2023-05-16 10:13 UTC, merged