Query scanner config API
Ostorlab/ostorlab pull request #443
Opened 2023-07-12 10:11 UTC by oussamaessaji

2023-07-12 17:27 UTC, 3asm approved these changes

2023-07-13 06:48 UTC, deadly-panda requested changes

2023-07-13 06:48 UTC, deadly-panda commented on src/ostorlab/apis/scanner_config.py
> +         query scanners($scannerId: Int){
Is the scannerId parameter required ? In that case, can you please add the `!` mark at the end.

2023-07-13 16:06 UTC, 3asm submitted a review, later dismissed

2023-07-13 18:04 UTC, mohsinenar requested changes

2023-07-13 18:04 UTC, mohsinenar commented on src/ostorlab/apis/scanner_config.py
> +class GetScannerConfigAPIRequest(request.APIRequest):
Can you find a better name? `get` is an action!

2023-07-13 18:46 UTC, mohsinenar approved these changes

2023-07-14 05:38 UTC, 3asm approved these changes

2023-07-14 13:51 UTC, merged