send scanner state
Ostorlab/ostorlab pull request #445
Opened 2023-07-12 13:14 UTC by ErebusZ

send scanner state

2023-07-12 13:22 UTC, amine3 requested changes

2023-07-12 13:22 UTC, amine3 commented on src/ostorlab/apis/add_scanner_state.py
> +
docstring missing

2023-07-12 13:22 UTC, amine3 commented on src/ostorlab/apis/add_scanner_state.py
> +from typing import Dict, Optional
missing docstring

2023-07-12 13:22 UTC, amine3 commented on src/ostorlab/apis/add_scanner_state.py
> +        """Defines the query to revoke the API key.
Incorrect docstring

2023-07-12 13:22 UTC, amine3 commented on src/ostorlab/runtimes/reporter.py
> +"""Reporter Doemon logic that report scanner state periodically."""
typo here

2023-07-12 13:22 UTC, amine3 commented on src/ostorlab/runtimes/reporter.py
> +            await self._capture_state()
The method is not async, it cannot bet awaited!

2023-07-12 16:16 UTC, amine3 requested changes

2023-07-12 16:16 UTC, amine3 commented on src/ostorlab/utils/reporter.py
> +"""Reporter daemon logic that report scanner state periodically."""
Reporter logic to read the scanner state periodically and send it to the backend.

2023-07-12 16:16 UTC, amine3 commented on src/ostorlab/utils/reporter.py
> +        runner = public_runner.PublicAPIRunner()
It should use the authenticated runner not the public one.

2023-07-12 16:16 UTC, amine3 commented on src/ostorlab/utils/reporter.py
> +            await self.capture_state()
Why capture state is public, and report_state is private?

2023-07-12 16:16 UTC, amine3 commented on src/ostorlab/utils/reporter.py
> +            await self._report_state()
Missing unittest for report state

2023-07-12 17:40 UTC, amine3 requested changes

2023-07-12 17:40 UTC, amine3 commented on tests/utils/reporter_test.py
> +    # mock.patch("psutil.cpu_percent", return_value=10)
remove this if not needed

2023-07-12 18:46 UTC, 3asm requested changes

2023-07-12 18:46 UTC, 3asm commented on src/ostorlab/utils/reporter.py
> +class Reporter:
Change class name, reporter is too generic.

2023-07-12 18:46 UTC, 3asm commented on src/ostorlab/utils/reporter.py
> +    def _capture_state(self) -> None:
What is the point of making part of self instead of returning the object?

2023-07-12 18:46 UTC, 3asm commented on src/ostorlab/utils/defintions.py
> +class State:
Should not be here.

2023-07-12 18:46 UTC, 3asm commented on src/ostorlab/utils/defintions.py
> +class State:
State is too generic of a name.

2023-07-13 07:01 UTC, deadly-panda requested changes

2023-07-13 07:01 UTC, deadly-panda commented on tests/utils/reporter_test.py
> +async def testReport_whenCalled_updateValues(mocker) -> None:
Can you please think of a more meaningful function name!

2023-07-13 07:01 UTC, deadly-panda commented on tests/utils/reporter_test.py
> +        mock.Mock(return_value="dummy"),
Check my comment about the mock package.

2023-07-13 07:01 UTC, deadly-panda commented on src/ostorlab/utils/reporter.py
> +            time.sleep(self.capture_interval)
Do we want the sleep to be blocking ?

2023-07-13 16:46 UTC, deadly-panda commented on tests/utils/scanner_state_reporter_test.py
> +        eturn_value="dummy",
How is this passing ? There is  a typo here: `eturn_value`

2023-07-13 16:47 UTC, deadly-panda commented on tests/utils/scanner_state_reporter_test.py
> +        eturn_value="dummy",
Also, can you type hint the function & add a one-line docstring please?

2023-07-13 16:48 UTC, deadly-panda commented on tests/utils/scanner_state_reporter_test.py
> +    state = ScannerState(
Can you please add new lines splitting the unit test into 3 parts: setup, call, asserts?

2023-07-14 05:42 UTC, 3asm approved these changes

2023-07-14 05:42 UTC, 3asm commented on src/ostorlab/utils/scanner_state_reporter.py
> +    async def run(self) -> None:
Both are missing docstrings.

2023-07-14 09:55 UTC, deadly-panda approved these changes

2023-07-14 16:02 UTC, amine3 approved these changes

2023-07-14 17:46 UTC, merged