Fix/change the behavior in the to fail if an argument is present in the settings but not in the agent definition
Ostorlab/ostorlab pull request #516
Opened 2023-10-31 12:18 UTC by oussamaessaji

2023-10-31 12:20 UTC, rabsondev requested changes

2023-10-31 12:20 UTC, rabsondev commented on src/ostorlab/agent/agent.py
> +        breakpoint()
Not needed, right?

2023-10-31 12:23 UTC, oussamaessaji commented on src/ostorlab/agent/agent.py
> +        breakpoint()
exactly

2023-10-31 13:50 UTC, 3asm commented
We can't do this yet.

2023-10-31 17:01 UTC, deadly-panda commented on src/ostorlab/agent/agent.py
> +    """Argument is present in the settings but not in the agent definition."""
Can be put in the exceptions module, since it's used in multiple places.

2023-11-01 14:05 UTC, ErebusZ requested changes

2023-11-01 14:05 UTC, ErebusZ commented on tests/runtimes/local/agent_runtime_test.py
> +def testLoaclRunTime_whenAgentArgsAreWrong_shouldFail(
where is the test for lite local runtime?

2023-11-01 15:52 UTC, amine3 commented on src/ostorlab/agent/agent.py
>                  logger.warning(
Why do we not raise here the error?

2023-11-02 05:56 UTC, amine3 requested changes
We need to fix inject store agent before merging this one

2023-11-03 08:33 UTC, amine3 approved these changes

2023-11-03 12:14 UTC, rabsondev approved these changes
lgtm

2023-11-03 13:00 UTC, ErebusZ approved these changes

2023-11-03 13:23 UTC, merged