Catch ConnectionResetError.
Ostorlab/ostorlab pull request #554
Opened 2024-01-16 13:55 UTC by mohsinenar

2024-01-16 17:00 UTC, benyissa submitted a review, later dismissed
The error message `ERROR Task exception was never retrieved` typically occurs when an exception is raised within an asynchronous task, but the exception is not explicitly caught or awaited, causing it to be missed.

currently in the code base we call `async_mq_send_message` in 2 cases  : 

if the event loop is currently running we use  `create_task` this will never raise the exception but it will be missed as explained above. 

if the event loop is currently running we use  `run_until_complete` this will return the Future's result, or raise its exception , in this case tenacity can be helpful.

if we want to catch them we can catch ConnectionError directly. but this will never fix this kind of issues if the `async_mq_send_message` was called using `create_task`.

2024-01-17 09:04 UTC, 3asm requested changes

2024-01-17 09:04 UTC, 3asm commented on src/ostorlab/agent/mixins/agent_mq_mixin.py
> +        retry=tenacity.retry_if_exception_type(
Needs unit test.

2024-01-17 09:36 UTC, benyissa reviewed
A new release for both `aiormq` and `aio-pika` was published 2 days ago. You can find the releases on the following GitHub repositories:

- `aiormq`: [https://github.com/mosquito/aiormq](https://github.com/mosquito/aiormq)
- `aio-pika`: [https://github.com/mosquito/aio-pika](https://github.com/mosquito/aio-pika)

We should review the change logs to determine if there are any modifications that could impact our current logic. If any such changes exist, it's advisable to pin the version accordingly.

2024-01-17 12:53 UTC, 3asm commented
Minor updates, just python version changes.

2024-01-19 08:59 UTC, elyousfi5 commented on tests/agent/mixins/agent_mq_mixin_test.py
> +def testMqSendMessage_onConnectionResetError_shouldRetriesAndReraise(mocker):
typing please

2024-01-21 11:26 UTC, 3asm approved these changes

2024-01-21 11:27 UTC, merged