Improve error handling in Docker Swarm initialization.
Ostorlab/ostorlab pull request #556
Opened 2024-01-19 17:21 UTC by mohsinenar

2024-01-19 17:30 UTC, 3asm requested changes

2024-01-19 17:30 UTC, 3asm commented on src/ostorlab/cli/docker_requirements_checker.py
> +        raise exceptions.OstorlabError("User does not have permission to run docker.")
Should be a custom DockerError.

2024-01-19 17:30 UTC, 3asm commented on src/ostorlab/cli/scan/run/run.py
> +        raise click.ClickException("Error:") from e
How is this one shown in the CLI?

2024-01-19 18:21 UTC, 3asm submitted a review, later dismissed

2024-01-22 09:15 UTC, elyousfi5 commented on tests/cli/docker_requirements_checker_test.py
> +):
```suggestion
) -> None:
```

2024-01-22 09:29 UTC, deadly-panda commented on src/ostorlab/cli/scan/run/run.py
> +        return None
Shouldn't we raise a `click.ClickException` here instead of returning None ?

2024-01-22 15:22 UTC, rabsondev requested changes

2024-01-22 15:22 UTC, rabsondev commented on tests/runtimes/local/runtime_test.py
> +):
```suggestion
def testRuntime_WhenCantInitSwarm_shouldShowUserFriendlyMessage(
    mocker: plugin.MockerFixture,
    requests_mock: req_mocker.Mocker,
) -> None:
```

2024-01-22 15:22 UTC, rabsondev commented on tests/runtimes/local/runtime_test.py
> +def testRuntime_WhenCantInitSwarm_shouldShowUserFriendlyMessage(
`_shouldShowUserFriendlyMessage` ... I don't see a check for the message in the unit test.

2024-01-24 12:35 UTC, 3asm approved these changes

2024-01-24 12:35 UTC, merged