Add binaries to the release assets
Ostorlab/ostorlab pull request #617
Opened 2024-03-11 17:53 UTC by ErebusZ

2024-03-11 20:00 UTC, 3asm requested changes

2024-03-11 20:00 UTC, 3asm commented on .github/workflows/release-linux-macos.yaml
> +        files: ${{ matrix.os }}.zip
Why generate a zip file if we have a single binary?

2024-03-12 11:01 UTC, 3asm submitted a review, later dismissed

2024-03-12 11:01 UTC, 3asm commented on .github/workflows/release_binary.yaml
> +        files: dist/${{ matrix.os }}-oxo
```suggestion
        files: dist/oxo_${{ matrix.os }}
```

2024-03-12 11:43 UTC, ErebusZ commented on .github/workflows/release_binary.yaml
> +        pyinstaller --name ${{ matrix.os }}-oxo --onefile --add-data="./*:." --hidden-import alembic --hidden-import docker --hidden-import click src/ostorlab/main.py
```suggestion
        pyinstaller --name oxo_${{ matrix.os }} --onefile --add-data="./*:." --hidden-import alembic --hidden-import docker --hidden-import click src/ostorlab/main.py
```

2024-03-12 14:56 UTC, 3asm approved these changes

2024-03-12 14:56 UTC, merged