Make `--follow` the default in OSS
Ostorlab/ostorlab pull request #618
Opened 2024-03-11 18:04 UTC by elyousfi5

Agent group definition of test:
![image](https://github.com/Ostorlab/ostorlab/assets/144013278/215aad4e-cfa9-4de8-a46d-e974b192c09e)

Command to start scan: `ostorlab scan run --install --unfollow agent/ostorlab/subfinder -g agent_group.yaml ip 8.8.8.8`

Result:
![image](https://github.com/Ostorlab/ostorlab/assets/144013278/ad7d8a2c-0242-48ba-8a6e-d17b462dee0e)
![image](https://github.com/Ostorlab/ostorlab/assets/144013278/97ae49ba-05c2-4104-a04a-ea4d0e8006dd)
![image](https://github.com/Ostorlab/ostorlab/assets/144013278/78f12c34-e86b-4278-b784-6eb2c910808e)

2024-03-11 18:53 UTC, oussamaessaji reviewed
Unit test?

2024-03-11 19:59 UTC, 3asm requested changes

2024-03-12 10:14 UTC, BlueSquare1 commented on src/ostorlab/cli/scan/run/run.py
> +    help="Don't show logs of provided list of agents and services.",
if it's boolean that would mean users can't decide to exclude only certain agent logs

2024-03-12 10:46 UTC, elyousfi5 commented on src/ostorlab/cli/scan/run/run.py
> +    help="Don't show logs of provided list of agents and services.",
@BlueSquare1 No we will keep follow, the logic will be as follow:
 # If unfollow is True, we don't follow any agent.
 # If follow is provided, we follow only the provided agents.
 # If neither follow or unfollow is provided the default is to follow all the agents.

2024-03-12 12:25 UTC, benyissa commented on src/ostorlab/cli/scan/run/run.py
> +    "--no-follow",
```suggestion
    "--unfollow",
```
--unfollow is more intuitive for me.

2024-03-12 13:07 UTC, elyousfi5 commented
> Unit test?

I added some videos as a demonstration.

2024-03-12 14:10 UTC, mohsinenar commented on src/ostorlab/cli/scan/run/run.py
Can you add a unit test?

2024-03-12 16:47 UTC, 3asm requested changes

2024-03-12 16:47 UTC, 3asm commented on src/ostorlab/cli/scan/run/run.py
> +    # Prepare and set the list of agents to follow.
The code needs unit test.

2024-03-12 16:47 UTC, 3asm commented on src/ostorlab/cli/scan/run/run.py
> +    agent_keys: List[str], follow: List[str], unfollow: bool
```suggestion
    agent_keys: List[str], follow: List[str], no_follow: bool
```

Keep it consistent.

2024-03-13 16:22 UTC, merged