Add shortcuts to agent keys option.
Ostorlab/ostorlab pull request #625
Opened 2024-03-12 15:47 UTC by benyissa

![image](https://github.com/Ostorlab/ostorlab/assets/144700714/029cafe7-7780-4e1b-9530-4ddd2b852d9a)

2024-03-12 16:03 UTC, ErebusZ submitted a review, later dismissed

2024-03-12 16:41 UTC, 3asm requested changes

2024-03-12 16:41 UTC, 3asm commented on src/ostorlab/cli/scan/run/run.py
> +    "used by default) | @org/key | agent/org/key",
```suggestion
    help="List agents keys (agent/<org>/<name> or @<org>/<name>). Org name can be omitted for defaults agent hosted by Ostorlab.",
```

2024-03-12 16:41 UTC, 3asm commented on src/ostorlab/cli/types.py
> +                    raise ValueError
```suggestion
                    raise ValueError("Invalid agent key value.")
```

2024-03-12 16:41 UTC, 3asm commented on src/ostorlab/cli/types.py
> +            )
Raise to fail. What kind of pattern is that :open_mouth: .

2024-03-13 10:11 UTC, deadly-panda requested changes

2024-03-13 10:11 UTC, deadly-panda commented on src/ostorlab/cli/scan/run/run.py
> +    type=types.AgentKeyTpe(),
You mean AgentKeyT**y**pe. Please fix!

2024-03-13 10:11 UTC, deadly-panda commented on tests/cli/scan/run/assets/ip_test.py
> +def testScanRunFile_whenAgentKeyPassed_callScanWithValidSettings(
update the test name, this is not scanning a file.

2024-03-13 10:11 UTC, deadly-panda commented on tests/cli/scan/run/run_test.py
> +)
Are you adding more cases? If not, why `parametrize`.

2024-03-13 11:38 UTC, elyousfi5 approved these changes
lgtm

2024-03-13 13:07 UTC, 3asm approved these changes

2024-03-13 13:08 UTC, merged